### PR TITLE
WIP: More closely approximate the AMQP 0-9-1 entity model

### PR DESCRIPTION
**Pull request by jessekempf**
Hi Sean,

First off, thanks for writing `amqp-worker`. It's a good set of refinements on top of `amqp`'s ubiquitous stringly typing.

I decided to take a crack at taking `amqp-worker` a bit further in using modern Haskell features to produce a more idiomatic AMQP binding. Now that I've gone to submit this, I see this overlaps with some work that you did last week. Ooops.

The starter for all of this on my part was that I'm migrating a legacy messaging environment from Python to Haskell, and I need to be able to support fanout exchanges. I essentially rewrote `Network.AMQP.Worker.Queue` as `Network.AMQP.Worker.Entity` to better map the AMQP 0-9-1 entity model into Haskell.

I've gotten this to the point of something of an ergonomics study, to see how the code feels to use. I wanted to get your feedback as soon as possible because of how substantial and backwards-incompatible the changes are.

Amongst other things, this PR adds the following:
1. Compile-time guarantees that `Exchange`s and `Queue`s have been declared before use.
2. Lenses for configuring `Exchange`s before declaring them.
3. Compile-time guarantees that `Queue`s can only be bound to `Exchange`s that produce their message type.
4. Support for Direct and Fanout exchanges in addition to Topic exchanges.
5. A mechanism for defining new exchange types straightforwardly. Routing keys are a function of the exchange type, so it would be typesafe to have the Default exchange take a `Queue` as its routing key, and for a `Headers` exchange to accept a `FieldTable` for its routing key.

What's lacking in this PR so far:
1. Lenses for configuring `Queue`s before use.
2. Updated usage documentation
3. Documentation for the new types, typeclasses, and functions.
4. An AMQP 0-9-1 compliant opaque routing key type. Max length is 255 octets. To truly enforce this we need a `Text -> Maybe AMQPRoutingKey` function, and a quasiquoter instead of `IsString`, since `fromString` can only do a validity check at runtime.
5. Support for `Headers` and `Default` exchanges.
6. Worker-callback-level support for selective acknowledgement of delivered messages.
7. Support for non-JSON messages.

The lenses I've provided use the `microlens` library. They're the only safe way of allowing the user to adjust a subset of `Exchange` or `Queue` and enforcing a separation between `Defined` and `Declared` AMQP entities. Microlens avoids the kitchen sink of dependencies that `Lens` has.

I look forward to working with you to see what we can get merged in and available on Hackage.

### CODE REVIEW

**Comment by seanhess** [comment]
Hi @jessekempf! Thanks for your work on this. It's a bummer our refactoring overlapped, but I think there are good ideas in both "branches" (my work is in master). I haven't updated the docs yet, but Example.hs demonstrates the API difference. 

The biggest change came from the realization that Queues don't belong to exchanges. They have a many-to-many relationship. I was also misunderstanding topic routing. The new commits change the API such that Keys do some of the work that Queues used to do: they have a phantom type indicating the message type, and you publish to a key.

I think we can take the best parts from both. 

One of my goals was to simplify the AMQP API. You can emulate a direct exchange using a topic exchange, so they seemed redundant. Can you help me understand how and why you are using a fanout exchange? I'd like to understand the use case better.

**Comment by seanhess** [comment]
I like the idea of compile-time guarantees that you've declared an exchange and queue before using it!

**Comment by jessekempf** [comment]
So here are some thoughts. I'm not advocating for a direction, just throwing this out there:

1. Queues are the avenue by which a consumer is connected to a stream of messages
2. Queues, at the same time, are associated with a message decoder. The decoder can be implicit, i.e., behavioral, or explicit and well-typed. If the program crashes when it receives a `poopytime` message, then that's its decoding behavior.
3. "Routing keys" are optional and there exists a mapping from exchange type to AMQP routing key type.
4. At the same time, routing keys truly belong to _bindings_, which is the one part of the AMQP 0-9-1 entity model we're treating implicitly in the code.
5. AMQP treats data purely opaquely, rules about message types are entirely up to us
6. It is true that, to be sane, a Queue must be capable of processing the union of all message types implied by its bindings.
7. It is true for all exchanges that a binding will pass a subset of the message types to its associated queue.
8. For exchanges that honor routing keys, it _may_ be true that a routing key causes a _strict_ subset of message types to be passed.
9. Publishing, by definition, is done to an `(exchange, routing_key)` pair. For some exchange types the `routing_key` is ignored.

So that's one set of things to consider.

Another is that AMQP-Worker is probably complecting three different considerations.

The first is a medium-level API that faithfully renders AMQP 0-9-1 rules in the Haskell type system. `Network.AMQP` doesn't really layer any structure over sending and receiving AMQP-formatted messages to the server.

The second is a high-level API that gives the user an opinionated way to implement some fairly common models of building stuff atop AMQP 0-9-1.

The third is a Reactor abstraction that lets one use the medium and high-level APIs within a message processor that gets spun off into its own thread.


There are a few reasons behind us going for Fanout exchanges. 
1. We're using AMQP for control-plane messages only, so broker-level filtering is not critical to system goodput.
2. Deciding what to do with a control-plane message is not a stateless matching problem. Both Topic (unidimensional) and Headers (multidimensional) exchanges operate on the model that if our message can be matched along N dimensions it should be delivered. The AMQP consumer itself has to decide whether it's interested in a message, and given (1) we're not trying to limit message rate at the broker.
3. Topic exchanges are less useful for control-plane messaging than they first seem. At first a system's members' interests can be described using a Topic exchange, but within about the first year of the system going live, use cases will start to crop up that can not be described by matching against an N-dimensional key. Because of (1), we're better off delivering messages that will be ignored than duplicating filtration logic.

Cheers,
-Jesse

**Comment by seanhess** [comment]
Thanks for our response!

I agree with everything with the slight exception of #4 - *binding keys* belong
to bindings, sure, but routing keys don't. They are always associated with
publishing, right?

You're correct in describing the 3 different considerations of amqp-worker.

Aside from the changes you included in your pull request, would you change
the structure of the project in some way? Split the project up into
multiple packages or something? While your first two lists were correct, I
don't quite understand what you're implying. You can suggest a direction, I
might not agree, but I'm curious what you think.

Super helpful information regarding fanout exchanges. So you basically
implement filtering logic in the message worker?

I don't really understand what "control plane messaging" means. I just
looked it up, and "control plane" seems to describe the part of the network
that handles routing. So... the exchange? But you're using the term more
specifically than that. What am I missing?

What do dimensions refer to in this context?

Thanks for your patience. I'm definitely not a messaging expert, but I want
to catch up and make sure this package is useful.

Cheers,
Sean

**Comment by jessekempf** [comment]
Routing keys show up twice, once in publishing, and once in binding. The broker consults them when it's deciding which messages from an exchange get inserted into which queues. RabbitMQ's AMQP 0-9-1 docs don't mention binding keys, so that's entirely a distinction we'd have to make in AMQP-Worker.

I'm not sure I'd go as far as to split AMQP-Worker up into multiple packages _yet_. But, at the same time, the mid-level API doesn't need a dependency on aeson since AMQP can pass protobufs, ASN.1, thrift, avro, bson, and other kinds of encoded data.

For my project, we're currently using JSON but we're going to flip over to Avro as soon as I get my arms around everything that uses AMQP.

Yes, for certain non-trivial use cases it's more straightforward to implement the filtering in the worker, rather than at the broker. That doesn't mean that broker-side filtering is purposeless, it just means that it's not a total solution.

Control plane in contradistinction to data plane. The canonical data-plane applications for AMQP would be stock market quotes and sporting events feeds. A control-plane application for AMQP would be a system that receives multigigabyte input files over SFTP, transfers them into an archive in S3, and then broadcasts a message to all listeners with the S3 URL and a large amount of metadata about the file that just arrived. Data plane load scales as O(N) in the volume of data the overall system handles. Control plane load scales as O(1) in the volume of data the overall system handles, because a 1 GB and 1 TB file both trigger a single message despite a three order of magnitude difference in size.

When I say dimension, I mean dimension in the sense of like the relational database model. On a topic exchange, the routing key for a published message is string-compared to the routing key on the binding. You can try to fake it, but you're mostly constrained to expressing a linear hierarchy of filters. On a headers exchange the matching is non-hierarchical.

Cheers,
-Jesse

**Comment by seanhess** [comment]
Hey @jessekempf!

I'm cleaning house after a few years away. Did you end up relying on your fork? Are you still working on the same project?

I've been away long enough that I probably might not use this package again (or would write a higher-level abstraction). If you're still using a fork, would you like to take this package over? If not I'll probably close the PR, as I lack the time or context to consider a large change like this.

**Comment by seanhess** [comment]
Updating for maintenance. Closing this for now.

**Pull request closed without merging**
